### ISSUE TITLE
Github-page of minBlockJS still showing (very) old code

### ISSUE THREAD

**Issue by ndsvw** [flouthoc/minBlock.js#13]
@flouthoc You made a github-site with a demo (here: [http://flouthoc.github.io/minBlock.js/](http://flouthoc.github.io/minBlock.js/)) but it's still showing (very) old code:
<img width="1160" alt="bildschirmfoto 2019-02-16 um 15 58 14" src="https://user-images.githubusercontent.com/21332313/52901421-b08f9000-3203-11e9-986c-ae0f460bc149.png">

Can you replace the code of that site with the code of the **index.html** file so that it looks like this?

<img width="1179" alt="bildschirmfoto 2019-02-16 um 16 00 50" src="https://user-images.githubusercontent.com/21332313/52901460-1845db00-3204-11e9-9a26-fd1f7bf69c3e.png">

**Comment by flouthoc** [comment]
You have to merge branches with gh-pages branch , please make a pull a request or i will do it

**Comment by flouthoc** [comment]
Please merge `master` with `gh-pages` or tell if you want me to do it.

**Comment by ndsvw** [comment]
> or tell if you want me to do it.

Yes, do it please..

**Comment by flouthoc** [comment]
@ndsvw  Could you please check again. Fixed in https://github.com/flouthoc/minBlock.js/pull/14

**Comment by ndsvw** [comment]
The only problem I could find:
This text appears 2 times in the index.html file...
<img width="512" alt="bildschirmfoto 2019-02-17 um 09 34 48" src="https://user-images.githubusercontent.com/21332313/52910418-7cfe4580-3297-11e9-8c21-1cc9178d64e6.png">

...in both branches. This code needs to be removed.
<img width="701" alt="bildschirmfoto 2019-02-17 um 09 37 04" src="https://user-images.githubusercontent.com/21332313/52910428-9c956e00-3297-11e9-81a8-2e9bb0cc92e7.png">

**Comment by flouthoc** [comment]
Ah I made this error when i was trying to remove the conflict. :disappointed:

**Comment by flouthoc** [comment]
Please check again and close this issue.

**Comment by ndsvw** [comment]
👍
